<a href="https://colab.research.google.com/github/robertkariuki726/DS_Course0_Week1_Module2_DataTypes/blob/main/SQLFilterOrderGroupLab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction

In this lab assessment you will explore writing more advanced SQL queries aimed at analyzing data on a more granular level. You will be working with 3 different databases throughout the assessment.
- planets.db: Contains data pertaining to planets in our solar system
- dogs.db: Contains data pertaining to famous fictional dog characters
- babe_ruth.db: Contains data pertaining to Babe Ruth's baseball career statistics

SQL (Structured Query Language) provides powerful tools for manipulating and analyzing data in relational databases. Four key operations for working with data are filtering, ordering, limiting, and grouping. These operations can be combined in a single query to perform complex data analysis and extraction tasks, allowing for powerful and flexible data manipulation.

## Learning Objectives

* Retrieve a subset of records from a table using a WHERE clause
* Filter results using conditional operators
* Apply an aggregate function to the result of a query
* Order the results of your queries by using ORDER BY (ASC & DESC)
* Limit the number of records returned by a query using LIMIT
* Use Group BY statements in SQL to apply aggregate functions

## Part I: Basic Filtering

You will begin by looking at the planets data to perform some basic filtering queries.

Table Name: planets

In [2]:
# CodeGrade step0

# Run this cell without changes

import pandas as pd
import sqlite3

# Create the connection
# Note the connect is 'conn1' since there will be multiple .db used
conn1 = sqlite3.connect('planets.db')

# Select all
pd.read_sql("""SELECT * FROM planets; """, conn1)

   id     name       color  num_of_moons    mass  rings
0   1  Mercury        gray             0    0.55      0
1   2    Venus      yellow             0    0.82      0
2   3    Earth        blue             1    1.00      0
3   4     Mars         red             2    0.11      0
4   5  Jupiter      orange            68  317.90      0
5   6   Saturn       hazel            62   95.19      1
6   7   Uranus  light blue            27   14.54      1
7   8  Neptune   dark blue            14   17.15      1

### Step 1
Return all the columns for planets that have 0 moons.

In [3]:
# CodeGrade step1
# Replace None with your code
df_no_moons = pd.read_sql("""SELECT * FROM planets WHERE num_of_moons = 0;""", conn1)

### Step 2
Return the name and mass of each planet that has a name with exactly 7 letters. Avoid hard coding this filter subset as much as possible.

In [4]:
# CodeGrade step2
# Replace None with your code
df_name_seven = pd.read_sql("""SELECT name, mass FROM planets WHERE LENGTH(name) = 7;""", conn1)

## Part 2: Advanced Filtering

### Step 3

Return the name and mass for each planet that has a mass that is less than or equal to 1.00.

In [5]:
# CodeGrade step3
# Replace None with your code
df_mass = pd.read_sql("""SELECT name, mass FROM planets WHERE mass <= 1.00;""", conn1)

### Step 4

Return all the columns for planets that have at least one moon and a mass less than 1.00.

In [6]:
# CodeGrade step4
# Replace None with your code
df_mass_moon = pd.read_sql("""SELECT * FROM planets WHERE num_of_moons >= 1 AND mass < 1.00;""", conn1)

### Step 5

Return the name and color of planets that have a color containing the string "blue".

In [7]:
# CodeGrade step5
# Replace None with your code
df_blue = pd.read_sql("""SELECT name, color FROM planets WHERE color LIKE '%blue%';""", conn1)

## Part 3: Ordering and Limiting

This database has some fictional, yet generally famous, dogs.

Table Name: dogs

In [25]:
# CodeGrade step0

# Run this cell without changes

# Create a connection
# Note the connect is 'conn2' since they will be multiple .db used
conn2 = sqlite3.connect('dogs.db')

# Select all
pd.read_sql("SELECT * FROM dogs;", conn2)

   id        name  age gender             breed  temperament  hungry
0   1      Snoopy    3      M            beagle     friendly       1
1   2     McGruff   10      M        bloodhound        aware       0
2   3      Scooby    6      M        great dane       hungry       1
3   4  Little Ann    5      F         coonhound        loyal       0
4   5     Pickles   13      F         black lab  mischievous       1
5   6    Clifford    4      M           big red       smiley       1
6   7      Lassie    7      F            collie       loving       1
7   8       Snowy    8      F       fox terrier  adventurous       0
8   9        None    4      M  golden retriever      playful       1

### Step 6
Return the name, age, and breed of all dogs that are hungry (binary flag of 1) and sort them from youngest to oldest.

In [27]:
import sqlite3
conn2 = sqlite3.connect('dogs.db')
# CodeGrade step6
# Replace None with your code
df_hungry = pd.read_sql("""SELECT name, age, breed FROM dogs WHERE hungry = 1 ORDER BY age ASC;""", conn2)

### Step 7
Return the name, age, and hungry columns for hungry dogs between the ages of two and seven. This query should also sort these dogs in alphabetical order.

In [28]:
import sqlite3
conn2 = sqlite3.connect('dogs.db')
# CodeGrade step7
# Replace None with your code
df_hungry_ages = pd.read_sql("""SELECT name, age, hungry FROM dogs WHERE hungry = 1 AND age BETWEEN 2 AND 7 ORDER BY name ASC;""", conn2)

### Step 8

Return the name, age, and breed for the 4 oldest dogs. Sort the result alphabetically based on the breed.

In [29]:
import sqlite3
conn2 = sqlite3.connect('dogs.db')
# CodeGrade step8
# Replace None with your code
df_4_oldest = pd.read_sql("""SELECT name, age, breed FROM dogs ORDER BY age DESC LIMIT 4;""", conn2)

## Part 4: Aggregation

In the next few parts, you'll query data from a table populated with Babe Ruth's career hitting statistics. You'll use aggregate functions to pull interesting information from the table that basic queries cannot track.

Table Name: babe_ruth_stats

In [42]:
# CodeGrade step0

# Run this cell without changes

# Create a connection
# Note the connect is 'conn3' since they will be multiple .db used
conn3 = sqlite3.connect('babe_ruth.db')

# Select all
pd.read_sql("""PRAGMA table_info(babe_ruth_stats); """, conn3)

    cid     name     type  notnull dflt_value  pk
0     0       id  INTEGER        0       None   1
1     1     year  INTEGER        0       None   0
2     2     team     TEXT        0       None   0
3     3   league     TEXT        0       None   0
4     4  doubles  INTEGER        0       None   0
5     5  triples  INTEGER        0       None   0
6     6     hits  INTEGER        0       None   0
7     7       HR  INTEGER        0       None   0
8     8    games  INTEGER        0       None   0
9     9     runs  INTEGER        0       None   0
10   10      RBI  INTEGER        0       None   0
11   11  at_bats  INTEGER        0       None   0
12   12       BB  INTEGER        0       None   0
13   13       SB  INTEGER        0       None   0
14   14       SO  INTEGER        0       None   0
15   15      AVG     REAL        0       None   0

### Step 9

Return the total number of years that Babe Ruth played professional baseball

In [38]:
import sqlite3
conn3 = sqlite3.connect('babe_ruth.db')
# CodeGrade step9
# Replace None with your code
df_ruth_years = pd.read_sql("""SELECT COUNT(DISTINCT year) AS total_years FROM babe_ruth_stats;""", conn3)

### Step 10

Return the total number of homeruns hit by Babe Ruth during his career.

In [39]:
import sqlite3
conn3 = sqlite3.connect('babe_ruth.db')
# CodeGrade step10
# Replace None with your code
df_hr_total = pd.read_sql("""SELECT SUM(HR) AS total_homeruns FROM babe_ruth_stats;""", conn3)

## Part 5: Grouping and Aggregation

### Step 11

For each team that Babe Ruth has played on, return the team name and the number of years he played on that team, aliased as 'number_years'.

In [40]:
import sqlite3
conn3 = sqlite3.connect('babe_ruth.db')
# CodeGrade step11
# Replace None with your code
df_teams_years = pd.read_sql("""SELECT team, COUNT(DISTINCT year) AS number_years FROM babe_ruth_stats GROUP BY team;""", conn3)

### Step 12

For each team that Babe Ruth played on and averged over 200 at bats with, return the team name and average number of at bats, aliased as 'average_at_bats'.

In [44]:
import sqlite3
conn3 = sqlite3.connect('babe_ruth.db')
# CodeGrade step12
# Replace None with your code
df_at_bats = pd.read_sql("""SELECT team, AVG(at_bats) AS average_at_bats FROM babe_ruth_stats GROUP BY team HAVING AVG(at_bats) > 200;""", conn3)

#### Close the connections

In [ ]:
# Run this cell without changes

conn1.close()
conn2.close()
conn3.close()